;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        comment-dwim
        cycle-spacing
        dabbrev-expand
        delete-horizontal-space
        forward-sexp
        helm-confirm-and-exit-minibuffer
        kill-region
        tab-to-tab-stop
        transpose-sexps
        transpose-words
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        2C-two-columns
        c-electric-colon
        helm-find-files
        kmacro-end-or-call-macro
        mc/mark-next-lines
        mc/mark-previous-lines
        repeat
        ))
