;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sentence
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-end-of-statement
        comment-dwim
        csharp-maybe-insert-codedoc
        cycle-spacing
        dabbrev-expand
        delete-horizontal-space
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        helm-mini
        kill-region
        kill-sentence
        org-delete-char
        org-self-insert-command
        org-todo
        tab-to-tab-stop
        transpose-sexps
        transpose-words
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        2C-two-columns
        ace-jump-mode
        delete-rectangle
        helm-confirm-and-exit-minibuffer
        helm-find-files
        helm-show-kill-ring
        kmacro-end-or-call-macro
        mc/mark-next-lines
        mc/mark-previous-lines
        repeat
        ))
