(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(global-nlinum-mode)
(column-number-mode)
(powerline-gahag-theme)

(global-company-mode)
(global-flycheck-mode)
(yas-global-mode)
;;(semantic-mode)
(eldoc-mode)
(electric-pair-mode)
(delete-selection-mode)
(show-paren-mode)
(doom-themes-org-config)
;;(projectile-global-mode)
(helm-mode)
(recentf-mode t)
(desktop-save-mode t)
(global-auto-revert-mode t)
(elpy-enable)
